#!/bin/bash

# ReportBuilder Multi-Agent Initialization Script
# This script initializes all agent environments for parallel development

set -e

echo "🚀 Initializing ReportBuilder Multi-Agent Development Environment"
echo "================================================================="

# Define agent configurations
declare -A agents
agents["task-3"]="Properties Panel Agent:3003:task-3-properties-panel:--persona-frontend"
agents["task-4"]="Undo/Redo System Agent:3004:task-4-undo-redo:--persona-architect"
agents["task-5"]="Database Setup Agent:3005:task-5-database-setup:--persona-backend"
agents["task-6"]="Data Binding Agent:3006:task-6-data-binding:--persona-backend"
agents["task-7"]="PDF Generation Agent:3007:task-7-pdf-generation:--persona-performance"
agents["task-8"]="Templates Agent:3008:task-8-templates:--persona-frontend"

# Base directory for all agents
BASE_DIR="/Users/peak/dev"
MAIN_REPO="$BASE_DIR/reportbuilder"

echo "📋 Agent Configuration Summary:"
echo "================================"
for task in "${!agents[@]}"; do
    IFS=':' read -r name port branch persona <<< "${agents[$task]}"
    echo "• $name"
    echo "  - Worktree: $BASE_DIR/reportbuilder-$task"
    echo "  - Port: $port"
    echo "  - Branch: $branch"
    echo "  - Persona: $persona"
    echo ""
done

# Function to initialize individual agent
init_agent() {
    local task=$1
    IFS=':' read -r name port branch persona <<< "${agents[$task]}"
    local agent_dir="$BASE_DIR/reportbuilder-$task"
    
    echo "🔧 Initializing $name..."
    echo "----------------------------------------"
    
    # Check if worktree exists
    if [ ! -d "$agent_dir" ]; then
        echo "❌ Worktree not found: $agent_dir"
        echo "   Please run the orchestration setup first"
        return 1
    fi
    
    # Navigate to agent directory
    cd "$agent_dir"
    
    # Check if node_modules exists, install if not
    if [ ! -d "node_modules" ]; then
        echo "📦 Installing dependencies..."
        npm install
    else
        echo "✅ Dependencies already installed"
    fi
    
    # Verify package.json port configuration
    if grep -q "\"dev\": \"next dev -p $port\"" package.json; then
        echo "✅ Port $port configured correctly"
    else
        echo "⚠️  Port configuration might be incorrect"
    fi
    
    # Create agent-specific directories if needed
    echo "📁 Creating agent-specific directories..."
    
    case $task in
        "task-3")
            mkdir -p components/designer/properties/advanced
            mkdir -p lib/property-management
            mkdir -p hooks/properties
            ;;
        "task-4")
            mkdir -p lib/commands
            mkdir -p lib/state
            mkdir -p components/designer/toolbar
            mkdir -p types/commands
            ;;
        "task-5")
            mkdir -p lib/database
            mkdir -p prisma
            mkdir -p data/mock
            mkdir -p scripts
            mkdir -p api/routes
            ;;
        "task-6")
            mkdir -p lib/data-binding
            mkdir -p lib/data-sources
            mkdir -p components/data-mapping
            mkdir -p types/data-binding
            ;;
        "task-7")
            mkdir -p lib/pdf-generation
            mkdir -p lib/renderers
            mkdir -p workers
            mkdir -p components/export
            ;;
        "task-8")
            mkdir -p templates
            mkdir -p components/templates
            mkdir -p lib/templates
            mkdir -p data/sample-templates
            ;;
    esac
    
    # Create agent-specific README
    cat > "AGENT-README.md" << EOF
# $name

## Quick Start
\`\`\`bash
npm run dev  # Starts development server on port $port
\`\`\`

## Agent Configuration
- **Task**: #${task#task-} - See /orchestration/agent-configs/${task/task-/}-agent.md
- **Port**: $port
- **Branch**: $branch
- **Persona**: $persona
- **Specialization**: $(grep "Specialization Focus" "../reportbuilder/orchestration/agent-configs/${task/task-/}*-agent.md" | cut -d':' -f2 || echo "See agent config file")

## Development URLs
- **This Agent**: http://localhost:$port
- **Main Repo**: http://localhost:3000 (if running)
- **Orchestration Config**: ../reportbuilder/ORCHESTRATION-CONFIG.md

## Agent Status
- [ ] Environment initialized
- [ ] Dependencies installed  
- [ ] Development server tested
- [ ] Agent configuration reviewed
- [ ] Initial development started

## Commands
\`\`\`bash
npm run dev        # Development server (port $port)
npm run build      # Production build
npm run lint       # ESLint check
npm run test       # Run tests
npm run type-check # TypeScript check
\`\`\`

---
Generated by ReportBuilder Multi-Agent Orchestration System
EOF

    echo "✅ $name initialized successfully"
    echo ""
    
    return 0
}

# Function to test agent environment
test_agent() {
    local task=$1
    IFS=':' read -r name port branch persona <<< "${agents[$task]}"
    local agent_dir="$BASE_DIR/reportbuilder-$task"
    
    echo "🧪 Testing $name environment..."
    
    cd "$agent_dir"
    
    # Test TypeScript compilation
    if npm run type-check >/dev/null 2>&1; then
        echo "✅ TypeScript compilation successful"
    else
        echo "⚠️  TypeScript compilation issues detected"
    fi
    
    # Test linting
    if npm run lint >/dev/null 2>&1; then
        echo "✅ ESLint check passed"
    else
        echo "⚠️  ESLint issues detected"
    fi
    
    # Test build
    if npm run build >/dev/null 2>&1; then
        echo "✅ Build successful"
    else
        echo "❌ Build failed"
        return 1
    fi
    
    echo "✅ $name environment test completed"
    echo ""
}

# Main execution
main() {
    echo "🔄 Starting agent initialization..."
    echo ""
    
    # Initialize all agents
    for task in "${!agents[@]}"; do
        if ! init_agent "$task"; then
            echo "❌ Failed to initialize agent $task"
            exit 1
        fi
    done
    
    echo "🧪 Running environment tests..."
    echo "==============================="
    
    # Test all agents
    for task in "${!agents[@]}"; do
        if ! test_agent "$task"; then
            echo "❌ Environment test failed for agent $task"
            exit 1
        fi
    done
    
    echo "🎉 Multi-Agent Environment Successfully Initialized!"
    echo "===================================================="
    echo ""
    echo "Next Steps:"
    echo "1. Review agent configurations in /orchestration/agent-configs/"
    echo "2. Start individual agents using their respective npm run dev commands"
    echo "3. Begin parallel development following the orchestration plan"
    echo ""
    echo "Agent URLs:"
    for task in "${!agents[@]}"; do
        IFS=':' read -r name port branch persona <<< "${agents[$task]}"
        echo "• $name: http://localhost:$port"
    done
    echo ""
    echo "📚 Documentation: $MAIN_REPO/ORCHESTRATION-CONFIG.md"
}

# Execute main function
main "$@"